In [12]:
from ppget.source import ModelSource

start_date = "2007-07-01"
end_date = "2008-07-01"
feature = "Global_active_power"

source = ModelSource.load(start_date, end_date, feature)
source.missing_data()

Series([], Freq: 10T, Name: Global_active_power, dtype: float64)

In [13]:
from sklearn.cluster import KMeans
import pandas as pd
from tensorflow import one_hot

daily_slices = 4

series = source.series()
kw_hour = pd.DataFrame(zip(list(series.values),list(series.index.hour)))
d_kmeans = KMeans(n_clusters=4).fit(kw_hour)
d = one_hot(d_kmeans.labels_, daily_slices)
d.shape, d[0]

(TensorShape([52704, 4]),
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 0., 0., 0.], dtype=float32)>)

In [14]:
monthly_slices = 4

kw_month = pd.DataFrame(zip(list(series.values),list(series.index.month)))
m_kmeans = KMeans(n_clusters=4).fit(kw_hour)
m = one_hot(m_kmeans.labels_, monthly_slices)
m.shape, m[0]

(TensorShape([52704, 4]),
 <tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 0., 0.], dtype=float32)>)

In [43]:
from ppget.datastructure import DatasetBuilder, TrainSplit

builder = DatasetBuilder(series, data_split=TrainSplit(), window_size=1)
builder.X.flatten()

array([0.30691728, 0.30323409, 0.3004301 , ..., 0.18149847, 0.14302688,
       0.1376803 ])